# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0010_auto_20160331_1639'),
        ('testapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=40)),
                ('traitnum', models.BigIntegerField(null=True)),
                ('link_to_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migration.Person')),
            ],
        ),
    ]
