# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0011_auto_20160331_1719'),
        ('testapp2', '0002_test3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migration.Person')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=40)),
                ('university_address', models.CharField(max_length=40)),
                ('university_telephone_number', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
