# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
