# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_person_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='telephone',
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
