# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_auto_20160330_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='test2',
            field=models.IntegerField(default=2),
        ),
    ]
