# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_auto_20160331_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=40)),
                ('course_description', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='class_directory',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='class_directory',
            name='Person',
        ),
        migrations.AddField(
            model_name='class',
            name='university',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AddField(
            model_name='class_directory',
            name='class_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migration.Class'),
        ),
        migrations.AddField(
            model_name='class_directory',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migration.Person'),
        ),
        migrations.AlterField(
            model_name='class',
            name='graduation_year',
            field=models.IntegerField(),
        ),
    ]
