# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0005_auto_20160331_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=40)),
                ('university_address', models.CharField(max_length=40)),
                ('university_telephone_number', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migration.University'),
        ),
        migrations.AddField(
            model_name='course_catalog',
            name='university',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='migration.University'),
        ),
    ]
