# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0008_friends'),
        ('migration', '0004_auto_20160331_1608'),
    ]

    operations = [
    ]
