# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0009_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='university',
        ),
        migrations.RemoveField(
            model_name='class_directory',
            name='class_index',
        ),
        migrations.RemoveField(
            model_name='person',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='test2',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
