# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0010_auto_20160331_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_directory',
            name='person',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='Class_Directory',
        ),
    ]
